WORKSPACE_DIR = ".jri"

CONFIG_FILE = f"{WORKSPACE_DIR}/config.yaml"
GITIGNORE_FILE = f"{WORKSPACE_DIR}/.gitignore"
LOGS_DIR = f"{WORKSPACE_DIR}/logs"
NOTEBOOK_FILE = f"{WORKSPACE_DIR}/notebook.yaml"
SECRETS_FILE = f"{WORKSPACE_DIR}/secrets.yaml"
SESSION_FILE = f"{WORKSPACE_DIR}/session.json"
VISUALIZATION_FILE = f"{WORKSPACE_DIR}/visualization.html"

SPECS_DIR = f"{WORKSPACE_DIR}/specs"
ARCHITECTURE_SPECS_DIR = f"{SPECS_DIR}/architecture"
FUNCTIONAL_SPECS_DIR = f"{SPECS_DIR}/functional"
